frame_id: world_frame
point_cloud_descriptions:
  - x: 0.4
    y: -1.6
    z: 0.9
    rx: 0.0
    ry: 0.0
    rz: 0.15
    l: 0.1
    w: 0.19
    h: 0.0
    resolution: 0.001
  - x: 0.0
    y: -1.3
    z: 0.75
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.2
    w: 0.1
    h: 0.0
    resolution: 0.001
  - x: -0.35
    y: -1.4
    z: 0.75
    rx: 0.0
    ry: 0.0
    rz: 0.1
    l: 0.2
    w: 0.5
    h: 0.0
    resolution: 0.001
