controller_list:
  - name: fake_manipulator_controller
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6
  - name: fake_manipulator_ensenso_controller
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6
  - name: fake_manipulator_zivid_controller
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6
  - name: fake_manipulator_blender_controller
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6
  - name: fake_manipulator_scancontrol_controller
    joints:
      - abb_irb4600_joint_1
      - abb_irb4600_joint_2
      - abb_irb4600_joint_3
      - abb_irb4600_joint_4
      - abb_irb4600_joint_5
      - abb_irb4600_joint_6